### PR TITLE
.travis.yml: Use cleaner if syntax.

### PR DESCRIPTION
**Pull request by dylanaraps**
I don't know if this syntax works or not but travis should test the PR and we'll find out.

### CODE REVIEW

**Comment by dylanaraps** [comment]
Oh, doesn't travis build for this repo yet? doh.

**Comment by iandrewt** [comment]
Closed and reopened, looks like there's an error

**Comment by iandrewt** [comment]
Yeah looks like it doesn't accept Bash syntax, it uses a different language called YAML

**Comment by dylanaraps** [comment]
Ah, that's a shame.

**Pull request closed without merging**
