### PR TITLE
fixed windows output

### PR DESCRIPTION
**Pull request by iandrewt**
@dar-irl can you test this please?

Solves #3

### CODE REVIEW

**Comment by dar-irl** [comment]
Awesome, gpmdp works by itself now, thanks! Does Neofetch's "Song" function get the song from gpmdp too? Even though gpmdp is working, Neofetch still says that no song is playing.

**Comment by dylanaraps** [comment]
Yes, neofetch uses gpmd-bash for the google play portion of the script.

**Comment by iandrewt** [comment]
The reason it's not showing yet is because Neofetch is using the version of gpmdp-bash you have installed, not the one you're testing. I'll push this to master and make a new release now, you can update to that and it will work fine.

**Comment by dar-irl** [comment]
After updating to the newest gpmdp-bash release, Neofetch still says "Song: Not Playing".

**Comment by iandrewt** [comment]
Odd... Can you provide the output of `gpmdp-bash current` and `neofetch --stdout song` while a song is playing please?

**Comment by dylanaraps** [comment]
Do you have any other music players running in the background?

**Comment by dar-irl** [comment]
`gpmdp-bash current` spits out "unknown command", but `gmpdp current` displays the song information correctly.

`neofetch --stdout song` returns "Not Playing⏎   "

No other music players are running in the background.

**Comment by iandrewt** [comment]
Maybe neofetch detection of whether Google Play Music is open on Windows is broken, it work fine on OS X and Linux.

And `gpmdp-bash` wouldn't have worked anyway, I keep forgetting the command is different to the project 😜

**Comment by dylanaraps** [comment]
The process name may be different on Windows, I'm not at home right now so I can't do any testing.

**Comment by dar-irl** [comment]
Looks like `ps x` won't work on Cygwin since it only lists processes running _in_ Cygwin. `ps -W` will list Windows processes as well. Here's a quick working solution I came up with:
```
elif [ -n "$(ps -W | awk '!(/awk/ || /Helper/) && /Google%20Play%20Music%20Desktop%20Player/')" ] && type -p gpmdp >/dev/null 2>&1; then
        song="$(gpmdp current)"
        state="$(gpmdp status)"	
```

**Comment by dylanaraps** [comment]
That only works on Windows though as `ps -W` is a CYGWIN exclusive flag. 
Does `ps -aux` list all of the running processes?

**Comment by iandrewt** [comment]
The other option would be to put a case around them to make for Windows specific functions

**Comment by dylanaraps** [comment]
We should come up with a solution that works on all platforms as CYGWIN users can also run cli music players and etc.

**Pull request merged**
